"""Is extrapolating the Translation below its fitted range what costs the 3-4 m band its sign?

Ticket #52. `served_path.py` found the learned Amplification Model **worse than the baseline**
in the 3-4 m measured-target band once the Translation step is included — +0.030 scored,
-0.043 served, the only band that changes sign against the learned model. The suspect named on
the ticket is extrapolation: the Translation is fitted on a big-swell subset and applied to
every hour the system serves.

This module tests that suspect and reports the answer. It ships nothing. Changing the
Translation would move shipped decision thresholds through `calibrate.py`, which consumes the
same fit, so the threshold movement each alternative *would* cause is reported here as a
number and left there.

**What this measures, in the order the questions have to be asked.**

1. **How much of each band is served by extrapolation at all.** A measured target of 3-4 m is
   not the same subset as the input the Translation is fitted on, and the answer bounds the
   suspect's plausibility before any alternative is fitted.

2. **How far each transform lands from the reading it claims to produce**, on the hours where
   both products actually reported. This is the only section here that assumes nothing, and it
   is where the extrapolation defect either shows up or does not.

3. **Whether any other shape does better on the served path**, scored on every held-out band,
   with 6 m and above held as a constraint rather than averaged away.

4. **Where the published served figure for each band comes from** — the same band read six
   ways, each one assumption further out, so that the part of the published number belonging
   to the reconstruction can be separated from the part belonging to the system.

5. **What each alternative would do to the shipped Watch and Go Call bars**, because
   `calibrate.py` restates them through this same fit.

**The generator is a choice, and it decides the answer.** The served path reconstructs what
Open-Meteo would have read, because no operational archive exists here. `served_path.py`
generates that series with the shipped Translation and lets the learned model invert the
shipped Translation — self-consistent, and fair for the question it asks, which is baseline
against learned. It is *not* fair for the question this module asks. Scoring an alternative
transform against a series generated by the shipped one measures which line matches the
generator, and the shipped line would win by construction.

So the generator and the transform the model inverts are separated here. The generator is
whichever candidate section 2 shows tracks the real pairing best across *every* sea state, and
every candidate is then scored on that same generated series. The circular version is not
discarded — it is the first rung of section 4's ladder, because it is exactly what the
published served figures are, and the gap between it and the next rung is the reconstruction's
own contribution to them.

**This inherits `served_path.py`'s assumption everywhere except section 2.** There is no
historical archive for the serving provider at this location, so every served figure is a
bound under the assumption that the Translation residual is independent of sea state, not an
observation. The default run therefore scores the same candidates under a residual that grows
with the sea as well as a flat one, and under no residual at all, because a conclusion that
only holds for one of them belongs to the reconstruction rather than to the system.

Run:
    .venv/Scripts/python.exe analysis/amplification_model/translation_shape.py

    # The fitting, the hinge, the inversion and the shipped-bar arithmetic, self-tested.
    .venv/Scripts/python.exe analysis/amplification_model/translation_shape.py --check
"""

from __future__ import annotations

import argparse
import csv
import json
import math
import sys
from collections.abc import Callable
from dataclasses import dataclass
from pathlib import Path
from typing import Literal

import numpy as np

HERE = Path(__file__).resolve().parent
ROOT = HERE.parent.parent

sys.path.insert(0, str(HERE))
sys.path.insert(0, str(ROOT / "analysis" / "calibration"))
sys.path.insert(0, str(ROOT / "analysis" / "overlap"))
sys.path.insert(0, str(ROOT / "analysis" / "backtest"))
sys.path.insert(0, str(ROOT / "backend" / "src"))

import calibrate  # noqa: E402
import measure  # noqa: E402
import reanalysis  # noqa: E402
import served_path  # noqa: E402

THRESHOLDS = ROOT / "backend" / "src" / "nazarenow" / "thresholds.json"
SHAPES_CSV = HERE / "output" / "translation_shapes.csv"
SUPPORT_CSV = HERE / "output" / "translation_support.csv"
PAIRING_CSV = HERE / "output" / "translation_pairing_error.csv"
BARS_CSV = HERE / "output" / "translation_shipped_bars.csv"

KNOT_M = 3.0
"""Where the regime-aware candidate joins its two lines, in reanalysis Combined Sea.

The same 3 m that `measure.BIG_SWELL_HEIGHT_M` and `train.py`'s `BIG_SWELL_M` name, so the
piecewise candidate asks the narrowest possible question: keep the shipped line's regime and
fit the hours below it too, rather than replace the shipped line with a different one.
"""

BAND_M = (3.0, 4.0)
"""The band under investigation, in reanalysis Combined Sea, for the band-fitted candidate."""

DEFAULT_GENERATOR = "regime-aware"
"""Which candidate stands in for what Open-Meteo would have read.

Chosen on section 2's evidence rather than asserted: it is the only candidate that tracks the
real pairing to within 0.06 m below 2 m *and* stays level with the shipped line above 6 m,
where every single-line alternative gives ground. Picking `all-hours` instead would understate
the baseline at size and flatter the learned model exactly where the project's claim lives.

Deliberately not `shipped`. Generating the series with the transform under test and then
inverting it with the same transform is self-consistent by construction, which is fine for
`served_path.py`'s baseline-against-learned question and useless for this one. That run is kept
as the first rung of section 4's ladder, where it is what the published figures are.
"""

FITTED_BARS = {
    "minimum_significant_wave_height_m": 2.75,
    "watch_minimum_swell_period_s": 12.0,
    "go_call_minimum_swell_period_s": 13.5,
}
"""The bars `calibrate.py` chose, before translation, in reanalysis units.

Quoted rather than re-fitted: re-running the calibration to recover three numbers would need
the Gold Day record and the reanalysis cache to answer a question about arithmetic. `check()`
pins them by translating them through the *shipped* Translation and requiring the three wave
bars in `thresholds.json` back, so a recalibration that moved them fails here loudly instead
of leaving this module quoting a stale fit.

The light-wind exemption is absent on purpose. Its transform is fitted on wind against a
different pairing (`analysis/wind_products/`), no candidate here touches it, and it therefore
cannot move for any reason this ticket is about.
"""


# ---------------------------------------------------------------------------------------
# Shapes
# ---------------------------------------------------------------------------------------


@dataclass(frozen=True)
class Segment:
    """One straight piece of a transform, and the scatter left around it.

    `lower` is in reanalysis units — the side the transform maps *from* — and is `-inf` for
    the first segment so that a single-line shape is a one-segment shape rather than a
    special case.
    """

    lower: float
    slope: float
    intercept: float
    residual_rmse: float
    n: int


@dataclass(frozen=True)
class Shape:
    """A fitted transform from a reanalysis reading to the operational equivalent.

    Generalises `measure.Translation` in exactly one direction: it may be more than one line.
    Everything else is deliberately kept identical, because an alternative that could not be
    consumed by both `LearnedAmplification._restate` and `calibrate.translate` is not a
    candidate — it is a different ticket. `as_translation()` is what makes that concrete: a
    one-segment shape hands back the shipped type unchanged, and a multi-segment one refuses,
    which is the honest statement of what adopting it would cost.
    """

    variable: str
    name: str
    regime: str
    segments: tuple[Segment, ...]

    def __post_init__(self) -> None:
        if not self.segments:
            raise ValueError("a shape needs at least one segment")
        if any(segment.slope <= 0 for segment in self.segments):
            # Every consumer inverts this transform. A flat or descending segment makes the
            # inverse undefined or non-monotone, which would restate a larger sea as a
            # smaller one somewhere in the range.
            raise ValueError(f"{self.name}: a segment does not increase, so it cannot invert")

    @property
    def n(self) -> int:
        return max(segment.n for segment in self.segments)

    def _index(self, xs: np.ndarray) -> np.ndarray:
        """Which segment each reanalysis-side value falls in."""
        bounds = np.array([segment.lower for segment in self.segments[1:]])
        return np.searchsorted(bounds, xs, side="right")

    def apply(self, xs: np.ndarray) -> np.ndarray:
        """Reanalysis in, operational out."""
        xs = np.asarray(xs, dtype=float)
        index = self._index(xs)
        slope = np.array([s.slope for s in self.segments])[index]
        intercept = np.array([s.intercept for s in self.segments])[index]
        return slope * xs + intercept

    def scatter(self, xs: np.ndarray) -> np.ndarray:
        """The residual RMSE that applies at each reanalysis-side value."""
        xs = np.asarray(xs, dtype=float)
        return np.array([s.residual_rmse for s in self.segments])[self._index(xs)]

    def invert(self, ys: np.ndarray) -> np.ndarray:
        """Operational in, reanalysis out — the direction a Pipeline Run needs.

        The segment is chosen on the operational side, by mapping each boundary through the
        transform. `fit_hinge` joins its lines *at* the knot, so the two readings of the
        boundary agree and the inverse is the genuine inverse rather than an approximation of
        one; `__post_init__` rules out the non-monotone case that would break it.
        """
        ys = np.asarray(ys, dtype=float)
        boundaries = np.array(
            [segment.slope * segment.lower + segment.intercept for segment in self.segments[1:]]
        )
        index = np.searchsorted(boundaries, ys, side="right")
        slope = np.array([s.slope for s in self.segments])[index]
        intercept = np.array([s.intercept for s in self.segments])[index]
        return (ys - intercept) / slope

    def as_translation(self) -> measure.Translation | None:
        """The shipped type, when this shape is expressible in it."""
        if len(self.segments) != 1:
            return None
        segment = self.segments[0]
        return measure.Translation(
            variable=self.variable,
            slope=segment.slope,
            intercept=segment.intercept,
            n=segment.n,
            residual_rmse=segment.residual_rmse,
            regime=self.regime,
        )

    def describe(self) -> str:
        if len(self.segments) == 1:
            segment = self.segments[0]
            return (
                f"operational = {segment.slope:.4f} x reanalysis {segment.intercept:+.4f} "
                f"(fitted on {segment.n} {self.regime}, residual RMSE "
                f"{segment.residual_rmse:.3f})"
            )
        pieces = []
        for index, segment in enumerate(self.segments):
            where = (
                f"below {self.segments[index + 1].lower:g}"
                if index + 1 < len(self.segments)
                else f"at or above {segment.lower:g}"
            )
            pieces.append(
                f"{where}: {segment.slope:.4f} x reanalysis {segment.intercept:+.4f} "
                f"(n {segment.n}, residual RMSE {segment.residual_rmse:.3f})"
            )
        return f"piecewise, {self.regime} — " + "; ".join(pieces)


def _shape_from(variable: str, translation: dict) -> Shape:
    """A one-segment shape from an `amplification.json` translation block."""
    return Shape(
        variable=variable,
        name="shipped",
        regime=f"{translation['fitted_on_hours']} hours, per amplification.json",
        segments=(
            Segment(
                lower=-math.inf,
                slope=float(translation["slope"]),
                intercept=float(translation["intercept"]),
                residual_rmse=float(translation["residual_rmse"]),
                n=int(translation["fitted_on_hours"]),
            ),
        ),
    )


def fit_line(variable: str, name: str, regime: str, xs: list[float], ys: list[float]) -> Shape:
    """One least-squares line, through the same arithmetic the shipped Translation uses."""
    slope, intercept, rmse = measure.least_squares(xs, ys)
    return Shape(
        variable=variable,
        name=name,
        regime=regime,
        segments=(
            Segment(
                lower=-math.inf,
                slope=slope,
                intercept=intercept,
                residual_rmse=rmse,
                n=len(xs),
            ),
        ),
    )


def fit_hinge(
    variable: str, name: str, regime: str, xs: list[float], ys: list[float], knot: float
) -> Shape:
    """Two lines joined at `knot`, fitted together in one least-squares solve.

    Fitted as `a + b*x + c*max(0, x - knot)` rather than as two independent regressions. Two
    independent fits would leave a step at the join, and a transform with a step is not
    invertible there — two different seas would restate to the same reading, and one reading
    would restate to two seas. Sharing the intercept makes continuity structural rather than
    something to check afterwards.

    The knot is fixed rather than searched. Searching it on the same hours it is scored on
    would fit the knot to the noise, and 3 m is the boundary the question is about.
    """
    x = np.asarray(xs, dtype=float)
    y = np.asarray(ys, dtype=float)
    hinge = np.maximum(0.0, x - knot)
    if not (hinge > 0).any() or not (hinge == 0).any():
        raise ValueError(f"{name}: every hour falls on one side of the {knot:g} knot")
    design = np.column_stack([np.ones_like(x), x, hinge])
    (base, slope_low, step), *_ = np.linalg.lstsq(design, y, rcond=None)

    below, above = x < knot, x >= knot
    residuals = y - design @ np.array([base, slope_low, step])
    return Shape(
        variable=variable,
        name=name,
        regime=regime,
        segments=(
            Segment(
                lower=-math.inf,
                slope=float(slope_low),
                intercept=float(base),
                residual_rmse=float(np.sqrt(np.mean(residuals[below] ** 2))),
                n=int(below.sum()),
            ),
            Segment(
                lower=knot,
                slope=float(slope_low + step),
                # Continuity at the knot: the upper line is the lower one, pivoted there.
                intercept=float(base - step * knot),
                residual_rmse=float(np.sqrt(np.mean(residuals[above] ** 2))),
                n=int(above.sum()),
            ),
        ),
    )


# ---------------------------------------------------------------------------------------
# The candidates
# ---------------------------------------------------------------------------------------


@dataclass(frozen=True)
class Candidate:
    """One shape of Translation, for both quantities the Amplification Model restates."""

    name: str
    height: Shape
    period: Shape

    @property
    def shippable(self) -> bool:
        """Whether `fit_translations()` could return this without changing its contract."""
        return self.height.as_translation() is not None and self.period.as_translation() is not None


SUBSETS: tuple[tuple[str, str, Callable[[measure.Paired], bool]], ...] = (
    (
        "shipped",
        f"operational Swell height >= {measure.BIG_SWELL_HEIGHT_M:g} m",
        lambda h: h.operational_height >= measure.BIG_SWELL_HEIGHT_M,
    ),
    ("all-hours", "every overlapping hour", lambda h: True),
    (
        "combined-sea-3m",
        f"reanalysis Combined Sea >= {KNOT_M:g} m",
        lambda h: h.reanalysis_combined_sea >= KNOT_M,
    ),
    (
        "band-fitted",
        f"reanalysis Combined Sea {BAND_M[0]:g}-{BAND_M[1]:g} m",
        lambda h: BAND_M[0] <= h.reanalysis_combined_sea < BAND_M[1],
    ),
)
"""The subset each single-line candidate is fitted on.

`shipped` is first and is the shipped fit re-derived here rather than read from
`amplification.json`, so that every candidate in the table is built by the same code from the
same hours and any difference between them is the subset and nothing else. `check()` requires
it to reproduce the shipped constants.

**`shipped` selects on operational Swell height, not on Combined Sea**, and that is the code
rather than a transcription slip — `measure.fit_translations` filters `operational_height`,
which is Open-Meteo's `swell_wave_height`. `combined-sea-3m` is the same bar read the way
`train.py:95-101`, `amplification.json` and #52's own body all describe it, and it is a
different 4,941 hours. CONTEXT.md keeps Combined Sea and Swell apart for exactly this reason.
"""


PAIRINGS: dict[
    str,
    tuple[
        Callable[[measure.Paired], float],
        Callable[[measure.Paired], float],
        Callable[[Candidate], Shape],
    ],
] = {
    "significant_wave_height_m": (
        lambda h: h.reanalysis_combined_sea,
        lambda h: h.operational_combined_sea,
        lambda candidate: candidate.height,
    ),
    "swell_period_s": (
        lambda h: h.combined_period,
        lambda h: h.operational_period,
        lambda candidate: candidate.period,
    ),
}
"""The two quantities a Translation is fitted between, and where each lives.

Named once because three places need it and they must not drift: the fitting, the error
measurement in section 2, and the restatement at scoring time. Two of them reading the pairing
differently is exactly the class of defect `served_path.check` exists to catch between the two
feature encodings.
"""


def _columns(hours: list[measure.Paired]) -> dict[str, tuple[list[float], list[float]]]:
    """Each pairing drawn out of a subset of hours, ready to fit."""
    return {
        quantity: ([source(h) for h in hours], [target(h) for h in hours])
        for quantity, (source, target, _) in PAIRINGS.items()
    }


def build_candidates(hours: list[measure.Paired]) -> list[Candidate]:
    """Every shape under test, fitted on the same overlap hours.

    The regime-aware candidate hinges the **height** transform only, and takes the all-hours
    line for period. Hinging the period transform on its own period has no principled knot,
    and hinging it on Combined Sea — the regime that actually matters — would make the
    restated period jump as the sea crosses 3 m, which is a worse defect than the one being
    fixed. Combined Sea is also where the question lives: it carries a standardised
    coefficient of 1.089 against swell period's 0.057 (`output/feature_reliance.csv`).
    """
    candidates: list[Candidate] = []
    for name, regime, predicate in SUBSETS:
        subset = [h for h in hours if predicate(h)]
        if len(subset) < 2:
            raise RuntimeError(f"{name}: {len(subset)} hours is not enough to fit a line")
        columns = _columns(subset)
        candidates.append(
            Candidate(
                name=name,
                height=fit_line(
                    "significant_wave_height_m", name, regime, *columns["significant_wave_height_m"]
                ),
                period=fit_line("swell_period_s", name, regime, *columns["swell_period_s"]),
            )
        )

    columns = _columns(hours)
    all_hours_period = fit_line(
        "swell_period_s", "regime-aware", "every overlapping hour", *columns["swell_period_s"]
    )
    candidates.append(
        Candidate(
            name="regime-aware",
            height=fit_hinge(
                "significant_wave_height_m",
                "regime-aware",
                f"every overlapping hour, hinged at {KNOT_M:g} m",
                *columns["significant_wave_height_m"],
                knot=KNOT_M,
            ),
            period=all_hours_period,
        )
    )
    return candidates


# ---------------------------------------------------------------------------------------
# Support: how much of each band is served by extrapolation
# ---------------------------------------------------------------------------------------


@dataclass(frozen=True)
class Support:
    """One band, and how much of it sits outside the hours the shipped line was fitted on."""

    band: str
    rows: int
    below_nominal: float
    below_support: float
    median_input: float


def support(frame, target: np.ndarray, fitted_floor: float) -> list[Support]:
    """Where each band's *input* sits against the range the shipped Translation covers.

    Two floors, because the nominal one is not the real one. The nominal floor is the 3 m the
    ticket and the parameter file both name. The real one is `fitted_floor`: the shipped
    subset is selected on Swell height, so its Combined Sea coverage reaches lower than 3 m,
    and an hour at 2.8 m of Combined Sea is inside the fitted cloud rather than extrapolated
    from it. Reporting only the nominal floor would overstate the suspect.
    """
    combined = frame["hindcast_combined_sea_height_m"].to_numpy()
    rows: list[Support] = []
    for band, mask in served_path.subsets(frame, target).items():
        inputs = combined[mask]
        rows.append(
            Support(
                band=band,
                rows=int(mask.sum()),
                below_nominal=float((inputs < KNOT_M).mean()),
                below_support=float((inputs < fitted_floor).mean()),
                median_input=float(np.median(inputs)),
            )
        )
    return rows


# ---------------------------------------------------------------------------------------
# The transforms against the pairing they claim to describe
# ---------------------------------------------------------------------------------------


INPUT_BANDS = ((0.0, 1.0), (1.0, 2.0), (2.0, 3.0), (3.0, 4.0), (4.0, 5.0), (5.0, 6.0), (6.0, 99.0))
"""Bands of *reanalysis Combined Sea* over the overlap hours.

Not the bands the rest of this module reports. Those are measured-target bands over held-out
hours at the buoy; these are input bands over the hours where both products reported, which is
the only place a transform between them can be checked at all.
"""


@dataclass(frozen=True)
class PairingError:
    """One candidate's error against the reading it is trying to predict, in one band."""

    candidate: str
    quantity: str
    band: str
    n: int
    bias: float
    rmse: float


def pairing_error(hours: list[measure.Paired], candidates: list[Candidate]) -> list[PairingError]:
    """How far each transform lands from the operational reading it claims to produce.

    **This is the one measurement here that is not a bound.** Everything downstream depends on
    reconstructing a series Open-Meteo never published at this location. This does not: both
    products really reported on all 35,064 of these hours, so the error of a transform between
    them is observed. If extrapolating the shipped Translation below its fitted range is a real
    defect, it is visible here, in the band where it is extrapolating, with no assumption in
    the way.

    Bias is kept signed and reported beside RMSE for the reason `measure.score` keeps them
    apart: a transform that is noisy in a band and one that is displaced through it are
    different failures, and only the second is what extrapolating a fitted line does.
    """
    combined = np.array([h.reanalysis_combined_sea for h in hours])
    columns = _columns(hours)

    rows: list[PairingError] = []
    for quantity, (_, _, pick) in PAIRINGS.items():
        xs, ys = (np.array(column) for column in columns[quantity])
        for lower, upper in (*INPUT_BANDS, (0.0, 99.0)):
            mask = (combined >= lower) & (combined < upper)
            if not mask.any():
                continue
            band = "all hours" if (lower, upper) == (0.0, 99.0) else f"{lower:g}-{upper:g} m"
            for candidate in candidates:
                errors = pick(candidate).apply(xs[mask]) - ys[mask]
                rows.append(
                    PairingError(
                        candidate=candidate.name,
                        quantity=quantity,
                        band=band,
                        n=int(mask.sum()),
                        bias=float(np.mean(errors)),
                        rmse=float(np.sqrt(np.mean(errors**2))),
                    )
                )
    return rows


# ---------------------------------------------------------------------------------------
# Scoring on the served path
# ---------------------------------------------------------------------------------------


Scatter = Literal["flat", "proportional", "none"]
"""What the reconstruction adds on top of the transform.

`flat` is `served_path.py`'s assumption — the residual is independent of sea state. `none`
isolates the measured offset from the assumed scatter. `proportional` redistributes the same
residual so that it grows with the sea, which is the reading that would make a conclusion an
artefact of the assumption rather than a property of the system.
"""


@dataclass(frozen=True)
class Reconstruction:
    """How the operational series a candidate is scored against is generated.

    Separated from the transform under test so the two roles cannot be confused. The
    generator stands in for what Open-Meteo would have read; the candidate is what the
    Amplification Model would invert. `served_path.py` uses the shipped line for both, which
    is right for baseline-against-learned and circular for shape-against-shape.
    """

    generator: Candidate
    scatter: Scatter = "flat"

    @property
    def label(self) -> str:
        return f"{self.generator.name} / scatter {self.scatter}"

    def draw(self, rng, shape: Shape, values: np.ndarray) -> np.ndarray:
        operational = shape.apply(values)
        if self.scatter == "none":
            return operational
        spread = shape.scatter(values)
        if self.scatter == "proportional":
            # Same total residual energy, redistributed so that it grows with the sea
            # instead of sitting flat across it. The alternative reading of the same
            # measurement, and the one that would make the sign change an artefact.
            spread = spread * (values / max(float(np.mean(values)), 1e-9))
        return operational + rng.normal(0.0, 1.0, len(values)) * spread


def score_candidates(
    parameters: dict,
    frame,
    target: np.ndarray,
    candidates: list[Candidate],
    reconstruction: Reconstruction,
    trials: int = served_path.TRIALS,
    seed: int = served_path.SEED,
) -> tuple[dict[str, np.ndarray], dict[str, dict[str, list[float]]]]:
    """Every candidate against one generated series, band by band.

    One `rng` and one generated series per trial, shared by every candidate, so the candidates
    differ by their transform and not by their draw. The baseline never inverts anything, so
    its MAE is identical across candidates by construction — which is what makes the learned
    column comparable down the table.
    """
    ibi_hs = frame["hindcast_combined_sea_height_m"].to_numpy()
    ibi_period = frame["swell_period_s"].to_numpy()
    rng = np.random.default_rng(seed)
    bands = served_path.subsets(frame, target)

    collected: dict[str, dict[str, list[float]]] = {
        name: {"baseline": []} | {candidate.name: [] for candidate in candidates} for name in bands
    }

    for _ in range(trials):
        operational_hs = reconstruction.draw(rng, reconstruction.generator.height, ibi_hs)
        operational_period = reconstruction.draw(rng, reconstruction.generator.period, ibi_period)
        predictions = {"baseline": operational_hs}
        for candidate in candidates:
            predictions[candidate.name] = served_path.predict(
                parameters,
                candidate.height.invert(operational_hs),
                candidate.period.invert(operational_period),
                frame,
            )
        for name, mask in bands.items():
            for label, predicted in predictions.items():
                collected[name][label].append(float(np.abs(predicted[mask] - target[mask]).mean()))
    return bands, collected


# ---------------------------------------------------------------------------------------
# What each alternative would do to the shipped bars
# ---------------------------------------------------------------------------------------


def shipped_bars(candidate: Candidate) -> dict[str, float]:
    """The three wave bars a Pipeline Run would read, had this candidate been the fit.

    The rounding is `calibrate.translate`'s and belongs to it — height floored to
    `HEIGHT_STEP_M` because down is its permissive direction, periods to the one decimal the
    operational feed reports. It is restated rather than called because `translate` also
    translates the light-wind exemption, whose transform is fitted on a different pairing that
    no candidate here touches; handing it a stand-in to get three numbers back would put a
    fabricated wind figure into this module's output. `check()` pins this against the shipped
    file so the two cannot drift apart silently.
    """
    height = float(
        candidate.height.apply(np.array([FITTED_BARS["minimum_significant_wave_height_m"]]))[0]
    )
    watch = float(
        candidate.period.apply(np.array([FITTED_BARS["watch_minimum_swell_period_s"]]))[0]
    )
    go = float(candidate.period.apply(np.array([FITTED_BARS["go_call_minimum_swell_period_s"]]))[0])
    return {
        "minimum_significant_wave_height_m": int(height / calibrate.HEIGHT_STEP_M)
        * calibrate.HEIGHT_STEP_M,
        "watch_minimum_swell_period_s": round(watch, 1),
        "go_call_minimum_swell_period_s": round(go, 1),
    }


# ---------------------------------------------------------------------------------------
# Reporting
# ---------------------------------------------------------------------------------------


def pin_against_shipped(shipped: Candidate, parameters: dict) -> str:
    """Refuse to report anything unless the `shipped` candidate really is the shipped one.

    Every figure in this module is a comparison against `shipped`, and `shipped` is re-derived
    here from the overlap hours rather than read out of `amplification.json` — so that all five
    candidates are built by one piece of code from one set of hours and differ only in their
    subset. That is worth having, and it is only worth having if the re-derivation lands on the
    constants the backend actually applies. If it does not, the whole table is measuring this
    module against itself.
    """
    published = parameters["translations"]
    for variable, shape in (
        ("significant_wave_height_m", shipped.height),
        ("swell_period_s", shipped.period),
    ):
        segment = shape.segments[0]
        for label, here, there in (
            ("slope", segment.slope, published[variable]["slope"]),
            ("intercept", segment.intercept, published[variable]["intercept"]),
            ("residual RMSE", segment.residual_rmse, published[variable]["residual_rmse"]),
            ("hours", float(segment.n), float(published[variable]["fitted_on_hours"])),
        ):
            if abs(here - there) > 1e-9:
                raise RuntimeError(
                    f"the re-derived shipped Translation does not match amplification.json: "
                    f"{variable} {label} is {here!r} here against {there!r} shipped. Either the "
                    "overlap cache has changed since the model was exported, or this module "
                    "fits a different subset from `measure.fit_translations`."
                )
    return "The `shipped` candidate re-derives amplification.json's constants exactly.\n"


def pin_against_served_path(
    shipped: Candidate, parameters, frame, target: np.ndarray, trials: int
) -> str:
    """Reproduce `output/served_path_scores.csv` by running this module as the shipped path.

    The generalisation here separates two things `served_path.py` holds together — the
    transform that generates the operational series and the transform the model inverts — and
    that separation is the whole argument of this module. Collapsing it back, by generating
    with `shipped` and inverting with `shipped`, must land exactly on the published served
    figures. If it does not, the generalisation changed the arithmetic rather than only
    widening it, and every alternative scored against those figures would be scored against a
    different calculation that happens to look alike.
    """
    _, collected = score_candidates(
        parameters,
        frame,
        target,
        [shipped],
        Reconstruction(generator=shipped),
        trials=trials,
    )
    published = {row["subset"]: row for row in _published_served()}
    for band, results in collected.items():
        if band not in published:
            continue
        for label, key in (("baseline", "served_baseline_mae"), ("shipped", "served_learned_mae")):
            here = float(np.mean(results[label]))
            there = float(published[band][key])
            if abs(here - there) > 5e-5:
                raise RuntimeError(
                    f"scored as the shipped path, {band} {label} is {here:.4f} here against "
                    f"{there:.4f} in served_path_scores.csv — the generalisation moved the "
                    "arithmetic, not just its inputs"
                )
    return (
        f"Run as the shipped path it reproduces served_path_scores.csv over {trials} trials, "
        "so the\nalternatives below are comparable with the published served figures rather "
        "than a\nseparate calculation.\n"
    )


def _published_served() -> list[dict]:
    with served_path.OUTPUT.open(newline="", encoding="utf-8") as handle:
        return list(csv.DictReader(handle))


def _write(path: Path, rows: list[dict]) -> Path:
    path.parent.mkdir(parents=True, exist_ok=True)
    with path.open("w", newline="", encoding="utf-8") as handle:
        writer = csv.DictWriter(handle, fieldnames=list(rows[0]))
        writer.writeheader()
        writer.writerows(rows)
    return path


def reconstructions(by_name: dict[str, Candidate], generator_name: str) -> list[Reconstruction]:
    """Every version of the served path this module reports, in the order they build on each other.

    The published served figures come from the first. The headline comes from the second. The
    difference between the two is the reconstruction's own contribution, which is the quantity
    #52 needs and which no single run can show.
    """
    generator = by_name[generator_name]
    return [
        Reconstruction(generator=by_name["shipped"]),
        Reconstruction(generator=generator),
        Reconstruction(generator=generator, scatter="none"),
        Reconstruction(generator=generator, scatter="proportional"),
    ]


def build(generator_name: str, trials: int) -> int:
    parameters, frame = served_path.load()
    target = frame["proxy_target_height_m"].to_numpy()
    hours = measure.pair_hours(reanalysis.IBI)
    candidates = build_candidates(hours)
    by_name = {candidate.name: candidate for candidate in candidates}
    if generator_name not in by_name:
        raise SystemExit(f"unknown generator {generator_name!r}; choose from {sorted(by_name)}")
    names = [candidate.name for candidate in candidates]

    shipped = by_name["shipped"]
    fitted_hours = [h for h in hours if h.operational_height >= measure.BIG_SWELL_HEIGHT_M]
    fitted_floor = float(np.percentile([h.reanalysis_combined_sea for h in fitted_hours], 1))

    print(f"Overlap hours: {len(hours):,}   held-out rows: {len(frame):,}\n")
    print(pin_against_shipped(shipped, parameters))
    print(pin_against_served_path(shipped, parameters, frame, target, trials))
    print("The transforms\n")
    for candidate in candidates:
        flag = "" if candidate.shippable else "   [not expressible as a Translation]"
        print(f"  {candidate.name:<16} {candidate.height.regime}{flag}")
        print(f"      height  {candidate.height.describe()}")
        print(f"      period  {candidate.period.describe()}")

    # --- 1 -----------------------------------------------------------------------------------
    print(f"\n{'=' * 98}\n1. How much of each band the shipped Translation was never fitted on\n")
    print(
        f"The shipped subset is selected on operational Swell height, so measured in Combined "
        f"Sea it\nreaches down to {fitted_floor:.2f} m at its 1st percentile — the floor of its "
        f"real support, against\nthe {KNOT_M:g} m the ticket, `train.py` and `amplification.json` "
        f"all name.\n"
    )
    support_rows = support(frame, target, fitted_floor)
    print(f"{'band':<32}{'rows':>8}{'below 3.00 m':>14}{'below support':>15}{'median input':>14}")
    for row in support_rows:
        print(
            f"{row.band:<32}{row.rows:>8,}{row.below_nominal:>13.1%}{row.below_support:>15.1%}"
            f"{row.median_input:>14.2f}"
        )
    _write(
        SUPPORT_CSV,
        [
            {
                "band": row.band,
                "rows": row.rows,
                "input_below_3m": round(row.below_nominal, 4),
                "input_below_fitted_support": round(row.below_support, 4),
                "fitted_support_floor_m": round(fitted_floor, 4),
                "median_input_combined_sea_m": round(row.median_input, 4),
            }
            for row in support_rows
        ],
    )

    # --- 2 -----------------------------------------------------------------------------------
    print(
        f"\n{'=' * 98}\n2. Each transform against the pairing it claims to describe — "
        f"observed, not reconstructed\n"
    )
    print(
        "Both products really reported on every one of these hours, so this table carries no\n"
        "assumption at all. Bands are the *input* Combined Sea, over the overlap; every other\n"
        "table here bands the measured target over the held-out seasons.\n"
    )
    errors = pairing_error(hours, candidates)
    _write(
        PAIRING_CSV,
        [
            {
                "quantity": row.quantity,
                "candidate": row.candidate,
                "input_combined_sea_band": row.band,
                "hours": row.n,
                "bias": round(row.bias, 4),
                "rmse": round(row.rmse, 4),
            }
            for row in errors
        ],
    )
    for quantity in ("significant_wave_height_m", "swell_period_s"):
        print(f"  {quantity} — bias / RMSE against the operational reading\n")
        print(f"  {'input band':<14}{'hours':>8}" + "".join(f"{name:>18}" for name in names))
        bands_seen = [
            row.band for row in errors if row.candidate == names[0] and row.quantity == quantity
        ]
        for band in bands_seen:
            row_for = {
                row.candidate: row
                for row in errors
                if row.quantity == quantity and row.band == band
            }
            line = f"  {band:<14}{row_for[names[0]].n:>8,}"
            for name in names:
                line += f"{f'{row_for[name].bias:+.3f} / {row_for[name].rmse:.3f}':>18}"
            print(line)
        print()

    # --- 3 -----------------------------------------------------------------------------------
    runs = reconstructions(by_name, generator_name)
    scored: dict[str, dict[str, dict[str, float]]] = {}
    shape_rows: list[dict] = []
    bands: dict[str, np.ndarray] = {}
    for reconstruction in runs:
        bands, collected = score_candidates(
            parameters, frame, target, candidates, reconstruction, trials=trials
        )
        gains: dict[str, dict[str, float]] = {}
        for band in bands:
            baseline = float(np.mean(collected[band]["baseline"]))
            gains[band] = {"baseline": baseline}
            for name in names:
                learned = float(np.mean(collected[band][name]))
                gains[band][name] = baseline - learned
                spread = np.array(collected[band]["baseline"]) - np.array(collected[band][name])
                low, high = np.percentile(spread, [5, 95])
                shape_rows.append(
                    {
                        "generator": reconstruction.generator.name,
                        "scatter": reconstruction.scatter,
                        "candidate": name,
                        "band": band,
                        "rows": int(bands[band].sum()),
                        "served_baseline_mae": round(baseline, 4),
                        "served_learned_mae": round(learned, 4),
                        "served_gain_m": round(baseline - learned, 4),
                        "served_gain_p5": round(float(low), 4),
                        "served_gain_p95": round(float(high), 4),
                    }
                )
        scored[reconstruction.label] = gains
    _write(SHAPES_CSV, shape_rows)

    headline = runs[1]
    print(f"{'=' * 98}\n3. Every candidate on the served path — {headline.label}\n")
    print("Positive means the learned Amplification Model is closer to the buoy.\n")
    print(f"{'band':<32}{'rows':>7}{'baseline MAE':>14}" + "".join(f"{name:>16}" for name in names))
    for band in bands:
        gains = scored[headline.label][band]
        line = f"{band:<32}{int(bands[band].sum()):>7,}{gains['baseline']:>14.4f}"
        for name in names:
            line += f"{gains[name]:>+16.4f}"
        print(line)

    # --- 4 -----------------------------------------------------------------------------------
    print(f"\n{'=' * 98}\n4. Where the published figure for each band comes from\n")
    print(
        "Six readings of the same band, each one assumption further out than the last. The gap\n"
        "between `published` and `fair gen` is the reconstruction's own contribution to the\n"
        "published figure; the gap between `fair gen` and `best alt` is all any change of shape\n"
        "could buy; and `no scatter` against `best alt` is what the assumed residual costs. What\n"
        "is left against `scored` is none of those three — it is the real difference between the\n"
        "two products, which shifts the baseline's reading and cannot be transformed away.\n\n"
        "`best alt`, `no scatter` and `sized scatter` are the best candidate *for that band*,\n"
        "named in the last column. It is not always an alternative: where it reads `shipped`,\n"
        "nothing beat the shipped fit.\n"
    )
    published = {row["subset"]: row for row in _published_served()}
    ladder = (
        ("scored", "no Translation step at all — `train.py`'s table", None, None),
        (
            "published",
            "served_path.py: generated and inverted by the shipped line",
            runs[0].label,
            "shipped",
        ),
        (
            "fair gen",
            "same shipped line, generated by one that fits every sea",
            runs[1].label,
            "shipped",
        ),
        ("best alt", "the best alternative transform, same generator", runs[1].label, None),
        ("no scatter", "the offset alone, with the residual switched off", runs[2].label, None),
        ("sized scatter", "the residual grown with the sea instead of flat", runs[3].label, None),
    )
    for short, meaning, _, _ in ladder:
        print(f"  {short:<15}{meaning}")
    print()
    print(f"{'band':<30}" + "".join(f"{short:>13}" for short, *_ in ladder) + "   best alternative")
    for band in bands:
        if band not in published:
            continue
        best = max(names, key=lambda name: scored[runs[1].label][band][name])
        line = f"{band:<30}"
        for _, _, label, candidate in ladder:
            value = (
                float(published[band]["scored_gain_m"])
                if label is None
                else scored[label][band][candidate or best]
            )
            line += f"{value:>+13.4f}"
        print(line + f"   {best}")

    # --- 5 -----------------------------------------------------------------------------------
    print(f"\n{'=' * 98}\n5. What adopting each candidate would do to the shipped bars\n")
    print(
        "`calibrate.py` restates the fitted bars through this same fit, so no candidate here is\n"
        "only an Amplification Model change. Fitted bars, in reanalysis units: "
        + ", ".join(f"{name.split('_')[0]} {value:g}" for name, value in FITTED_BARS.items())
        + ".\n"
    )
    current = json.loads(THRESHOLDS.read_text(encoding="utf-8"))
    print(f"{'candidate':<16}{'height m':>12}{'Watch s':>12}{'Go Call s':>12}   shippable")
    bar_rows: list[dict] = []
    for candidate in candidates:
        bars = shipped_bars(candidate)
        moved = {name: bars[name] - float(current[name]) for name in FITTED_BARS}
        print(
            f"{candidate.name:<16}"
            f"{bars['minimum_significant_wave_height_m']:>7.2f}"
            f"{moved['minimum_significant_wave_height_m']:>+5.2f}"
            f"{bars['watch_minimum_swell_period_s']:>7.1f}"
            f"{moved['watch_minimum_swell_period_s']:>+5.1f}"
            f"{bars['go_call_minimum_swell_period_s']:>7.1f}"
            f"{moved['go_call_minimum_swell_period_s']:>+5.1f}"
            f"   {'yes' if candidate.shippable else 'no — two lines'}"
        )
        bar_rows.append(
            {
                "candidate": candidate.name,
                "shippable_as_translation": "yes" if candidate.shippable else "no",
                **{name: bars[name] for name in FITTED_BARS},
                **{f"moved_{name}": round(moved[name], 4) for name in FITTED_BARS},
            }
        )
    _write(BARS_CSV, bar_rows)

    print(
        f"\nwrote {SUPPORT_CSV.relative_to(ROOT)}, {PAIRING_CSV.relative_to(ROOT)},\n"
        f"      {SHAPES_CSV.relative_to(ROOT)}, {BARS_CSV.relative_to(ROOT)}"
    )
    print(
        "\nSection 2 is observed. Sections 3 to 5 are bounds: the serving provider has no\n"
        "historical archive at this location, so the operational series is reconstructed. See\n"
        "the module docstring and `README.md`."
    )
    return 0


# ---------------------------------------------------------------------------------------
# Self-test
# ---------------------------------------------------------------------------------------


def check() -> int:
    """The fitting, the hinge, the inversion and the rounding, offline and on known answers.

    Nothing here reads the overlap cache or the training dataset. The two checks that need
    real data — that the `shipped` candidate re-derives the constants in `amplification.json`,
    and that scoring it under its own generator reproduces `output/served_path_scores.csv` —
    run inside `build()`, where the data is present by definition.
    """
    failures: list[str] = []

    def expect(label: str, got: object, want: object) -> None:
        if got != want:
            failures.append(f"{label}: expected {want!r}, got {got!r}")

    def raises(label: str, call) -> None:
        try:
            call()
        except ValueError:
            return
        failures.append(f"{label}: expected a ValueError")

    # --- one line ------------------------------------------------------------------------
    line = fit_line("h", "known", "hours", [1.0, 2.0, 3.0], [3.0, 5.0, 7.0])
    expect("a known line's slope", round(line.segments[0].slope, 9), 2.0)
    expect("a known line's intercept", round(line.segments[0].intercept, 9), 1.0)
    expect("an exact line leaves no residual", round(line.segments[0].residual_rmse, 9), 0.0)
    expect("applying the line", round(float(line.apply(np.array([4.0]))[0]), 9), 9.0)
    expect(
        "inverting undoes applying",
        round(float(line.invert(line.apply(np.array([4.0])))[0]), 9),
        4.0,
    )
    expect(
        "a one-segment shape is still a Translation",
        line.as_translation().slope,
        line.segments[0].slope,
    )

    # A transform that does not increase cannot be inverted, and every consumer inverts it.
    raises(
        "a flat segment is refused",
        lambda: Shape(
            variable="h",
            name="flat",
            regime="hours",
            segments=(Segment(lower=-math.inf, slope=0.0, intercept=1.0, residual_rmse=0.0, n=2),),
        ),
    )

    # --- two lines -----------------------------------------------------------------------
    # y = x below 3, and y = 3 + 2(x - 3) above it: a broken stick the fit must recover
    # exactly, including the pivoted intercept of the upper piece.
    xs = [0.0, 1.0, 2.0, 3.0, 4.0, 5.0]
    ys = [0.0, 1.0, 2.0, 3.0, 5.0, 7.0]
    hinge = fit_hinge("h", "hinge", "hours", xs, ys, knot=3.0)
    expect("the lower slope", round(hinge.segments[0].slope, 9), 1.0)
    expect("the upper slope", round(hinge.segments[1].slope, 9), 2.0)
    expect(
        "the upper intercept is pivoted at the knot", round(hinge.segments[1].intercept, 9), -3.0
    )
    expect(
        "an exact broken stick leaves no residual", round(hinge.segments[0].residual_rmse, 9), 0.0
    )
    expect("a hinge is not expressible as a Translation", hinge.as_translation(), None)

    # Continuity is what makes the inverse a genuine inverse. Two independent regressions
    # would leave a step here, and a step makes two seas restate to one reading.
    below = hinge.segments[0].slope * 3.0 + hinge.segments[0].intercept
    above = hinge.segments[1].slope * 3.0 + hinge.segments[1].intercept
    expect("the two lines meet at the knot", round(below - above, 9), 0.0)

    probes = np.array([0.5, 2.999, 3.0, 3.001, 4.5])
    expect(
        "the hinge inverts on both sides of the knot",
        [round(v, 9) for v in hinge.invert(hinge.apply(probes))],
        [round(v, 9) for v in probes],
    )
    expect(
        "the knot itself takes the upper segment",
        [round(float(v), 9) for v in hinge.apply(np.array([3.0]))],
        [3.0],
    )
    raises(
        "a hinge needs hours on both sides",
        lambda: fit_hinge("h", "one-sided", "hours", [4.0, 5.0, 6.0], [4.0, 5.0, 6.0], knot=3.0),
    )

    # --- the rounding the shipped bars go through -----------------------------------------
    # Height floors to the 0.25 m step and periods go to one decimal, per `calibrate.translate`.
    identity = fit_line("significant_wave_height_m", "id", "hours", [0.0, 1.0], [0.02, 1.02])
    slightly_long = fit_line("swell_period_s", "id", "hours", [0.0, 1.0], [0.04, 1.04])
    bars = shipped_bars(Candidate(name="synthetic", height=identity, period=slightly_long))
    expect("height floors to the step", bars["minimum_significant_wave_height_m"], 2.75)
    expect("the Watch bar goes to one decimal", bars["watch_minimum_swell_period_s"], 12.0)
    expect("the Go bar goes to one decimal", bars["go_call_minimum_swell_period_s"], 13.5)

    # ...and the constants themselves, against the two files that between them decide whether
    # `FITTED_BARS` is still the fit. Both are in the repository, so this needs no cache: the
    # shipped Translation comes out of `amplification.json` and the answer out of
    # `thresholds.json`. A recalibration that moved the fitted bars, or a retrain that moved
    # the Translation, breaks this rather than leaving section 5 quoting a stale pair.
    shipped_translations = json.loads(served_path.PARAMETERS.read_text(encoding="utf-8"))[
        "translations"
    ]
    from_file = Candidate(
        name="shipped",
        height=_shape_from(
            "significant_wave_height_m", shipped_translations["significant_wave_height_m"]
        ),
        period=_shape_from("swell_period_s", shipped_translations["swell_period_s"]),
    )
    current = json.loads(THRESHOLDS.read_text(encoding="utf-8"))
    for name, value in shipped_bars(from_file).items():
        expect(f"the fitted {name} translates to the shipped bar", value, float(current[name]))

    # --- the reconstruction ----------------------------------------------------------------
    synthetic = Candidate(name="synthetic", height=line, period=line)
    values = np.array([1.0, 2.0, 3.0])
    rng = np.random.default_rng(0)
    expect(
        "noise off returns the transform exactly",
        [
            round(float(v), 9)
            for v in Reconstruction(synthetic, scatter="none").draw(rng, line, values)
        ],
        [round(float(v), 9) for v in line.apply(values)],
    )
    # The proportional variant redistributes the residual rather than adding to it, so the
    # scatter it draws with still averages to the flat one it replaces. Without that, a
    # sensitivity check would be confounded with simply turning the noise up.
    sized = fit_line("h", "scattered", "hours", [1.0, 2.0, 3.0, 4.0], [3.2, 4.8, 7.1, 8.9])
    flat = sized.scatter(values)
    weighted = flat * (values / float(np.mean(values)))
    expect(
        "the proportional residual carries the same mean scatter",
        round(float(np.mean(weighted) - np.mean(flat)), 9),
        0.0,
    )

    for failure in failures:
        print(f"FAIL {failure}")
    print("translation_shape.py --check: " + ("FAILED" if failures else "all checks passed"))
    return 1 if failures else 0


def main() -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--check", action="store_true", help="self-test the arithmetic offline")
    parser.add_argument(
        "--generator",
        default=DEFAULT_GENERATOR,
        help="which candidate generates the reconstructed operational series",
    )
    parser.add_argument("--trials", type=int, default=served_path.TRIALS)
    args = parser.parse_args()
    if args.check:
        return check()
    return build(generator_name=args.generator, trials=args.trials)


if __name__ == "__main__":
    raise SystemExit(main())
