/**
 * The wind, as a reader gets it.
 *
 * `wind-rules.test.ts` proves the rules. What is left for this file is what those cannot see:
 * that there is exactly one dart per point the endpoint actually returned, that each one
 * carries its own point's speed and bearing rather than the first point's, and that the legend
 * is generated by the same function as the map rather than by a second copy of the rule.
 */

import { render } from '@testing-library/react';
import { describe, expect, it } from 'vitest';

import { MapSlot } from './MapSlot';
import { Wind, WindLegend } from './Wind';
import { conditionsGrid } from './test/handlers';
import { dartHeadingDeg, driftSeconds } from './wind-rules';
import type { ConditionsGrid } from './api';

const GRID = conditionsGrid as unknown as ConditionsGrid;

function draw(grid: ConditionsGrid | null) {
  const { container } = render(
    <svg viewBox="0 0 686.8 780">
      <Wind grid={grid} />
    </svg>,
  );
  return container;
}

describe('Wind', () => {
  it('draws one dart per point the endpoint returned, and no more', () => {
    // "Never an interpolated field, and never more darts than points" — the honesty reason
    // darts were chosen over a flowing field in the first place.
    expect(GRID.points).toHaveLength(25);
    expect(draw(GRID).querySelectorAll('.wind-dart')).toHaveLength(25);
  });

  it('draws nothing at all when there is no grid to draw', () => {
    // The endpoint answers 503 rather than an empty grid, because a map with no darts cannot
    // be told from a map of a flat calm. Drawing a default calm here would be the same lie.
    expect(draw(null).querySelectorAll('.wind-dart')).toHaveLength(0);
  });

  it('gives every dart its own point, not the first point twenty-five times', () => {
    const darts = [...draw(GRID).querySelectorAll('.wind-dart')];
    const transforms = new Set(darts.map((d) => d.getAttribute('transform')));
    const durations = new Set(darts.map((d) => (d as HTMLElement).style.animationDuration));
    // The fixture varies speed and bearing at every point, so a component that read
    // `points[0]` for all of them would collapse both of these to one.
    expect(transforms.size).toBe(25);
    expect(durations.size).toBe(25);
  });

  it('points each dart downwind and drifts it at its own speed', () => {
    const darts = [...draw(GRID).querySelectorAll('.wind-dart')];
    GRID.points.forEach((point, index) => {
      const dart = darts[index] as HTMLElement;
      const expectedHeading = dartHeadingDeg(point.wind_direction.value);
      const expectedSeconds = driftSeconds(point.wind_speed.value);
      expect(dart.getAttribute('transform')).toContain(`rotate(${expectedHeading}`);
      expect(dart.style.animationDuration).toBe(`${expectedSeconds}s`);
    });
  });

  it('keeps every dart inside the drawn frame', () => {
    // ADR 0015: the whole frame is drawn precisely so that every fetched point is a point a
    // reader can see. A dart outside the viewBox would make that promise false again.
    for (const dart of draw(GRID).querySelectorAll('.wind-dart')) {
      const match = /translate\(([-\d.]+) ([-\d.]+)\)/.exec(dart.getAttribute('transform') ?? '');
      expect(match).not.toBeNull();
      const [x, y] = [Number(match![1]), Number(match![2])];
      expect(x).toBeGreaterThanOrEqual(0);
      expect(x).toBeLessThanOrEqual(686.8);
      expect(y).toBeGreaterThanOrEqual(0);
      expect(y).toBeLessThanOrEqual(780);
    }
  });

  it('takes its colour from a class, never an attribute', () => {
    for (const dart of draw(GRID).querySelectorAll('.wind-dart path')) {
      expect(dart.getAttribute('fill')).toBeNull();
      expect(dart.getAttribute('stroke')).toBeNull();
    }
  });
});

describe('WindLegend', () => {
  it('shows the three speeds the spec names', () => {
    const { container } = render(<WindLegend />);
    const text = container.textContent ?? '';
    for (const speed of [10, 25, 45]) {
      expect(text).toContain(String(speed));
    }
  });

  it('drifts each sample at the rate the map would drift it', () => {
    // "Built from the same function the map uses so the legend cannot disagree with the map."
    // A legend with its own copy of `33 / speed` would pass a test that hard-coded the answer.
    const { container } = render(<WindLegend />);
    const samples = [...container.querySelectorAll('.wind-dart')] as HTMLElement[];
    expect(samples).toHaveLength(3);
    [10, 25, 45].forEach((speed, index) => {
      expect(samples[index]!.style.animationDuration).toBe(`${driftSeconds(speed)}s`);
    });
  });
});

describe('a grid with nothing in it', () => {
  // The backend answers 503 rather than an empty grid, for exactly the reason this guards: a
  // map with no darts cannot be told from a map of a flat calm. That is the backend's promise,
  // and the page should not need it to be kept.
  it('says the wind is unavailable rather than drawing nothing quietly', () => {
    const empty = { ...GRID, points: [] };
    const { container, getByText } = render(
      <MapSlot swell={null} grid={empty} windUnavailable={false} />,
    );
    expect(container.querySelectorAll('.wind-dart')).toHaveLength(0);
    expect(getByText(/wind unavailable/i)).toBeInTheDocument();
  });

  it('still draws the legend and the darts when there are points', () => {
    const { container, queryByText } = render(
      <MapSlot swell={null} grid={GRID} windUnavailable={false} />,
    );
    expect(container.querySelectorAll('.wind-dart').length).toBeGreaterThan(25);
    expect(queryByText(/wind unavailable/i)).toBeNull();
  });
});
